# Development overrides
services:
  api:
    build:
      target: base
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/api:/app
    command: ["sh", "-c", "cd /app && PYTHONPATH=/app uv run --no-sync uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]

  web:
    build:
      target: deps
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next
    command: ["pnpm", "dev"]
    ports:
      - "3000:3000"
      - "3001:3001"  # For Next.js dev server

  postgres:
    ports:
      - "5432:5432"
      
  arangodb:
    ports:
      - "8529:8529"