name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: atspro_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Configure npm registry
        run: |
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc || true

      - name: Clear Bun cache
        run: |
          bun pm cache rm
          rm -rf ~/.bun/install/cache

      - name: Install dependencies
        env:
          CI: true
        run: |
          bun install --no-cache || bun install --no-cache

      - name: Setup environment
        run: |
          cp .env.example .env
          echo "DATABASE_URL=postgresql://test:test@localhost:5432/atspro_test" >> .env

      - name: Run database migrations
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/atspro_test
        run: |
          bun run migrate

      - name: Run unit tests
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/atspro_test
          PUBLIC_BETTER_AUTH_URL: http://localhost:5173
          ANTHROPIC_API_KEY: test-key
          BETTER_AUTH_SECRET: test-secret-key-that-is-at-least-32-chars
          BETTER_AUTH_URL: http://localhost:5173
          OPENAI_API_KEY: test-key
        run: bun run test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Configure npm registry
        run: |
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc || true

      - name: Clear Bun cache
        run: |
          bun pm cache rm
          rm -rf ~/.bun/install/cache

      - name: Install dependencies
        env:
          CI: true
        run: |
          bun install --no-cache || bun install --no-cache

      - name: Setup environment
        run: |
          cp .env.example .env

      - name: Run linter
        run: bun run lint

      - name: Check TypeScript
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/atspro_test
          PUBLIC_BETTER_AUTH_URL: http://localhost:5173
          ANTHROPIC_API_KEY: test-key
          BETTER_AUTH_SECRET: test-secret-key-that-is-at-least-32-chars
          BETTER_AUTH_URL: http://localhost:5173
          OPENAI_API_KEY: test-key
        run: bun run check
