name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: atspro_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Configure npm registry
        run: |
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc || true

      - name: Clear Bun cache
        run: |
          bun pm cache rm
          rm -rf ~/.bun/install/cache

      - name: Install dependencies
        run: |
          bun install --no-cache || bun install --no-cache

      - name: Setup environment
        run: |
          cp .env.example .env
          echo "DATABASE_URL=postgresql://test:test@localhost:5432/atspro_test" >> .env

      - name: Run database migrations
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/atspro_test
        run: |
          bun run db:migrate

      - name: Run unit tests
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/atspro_test
          PUBLIC_BETTER_AUTH_URL: http://localhost:5173
          ANTHROPIC_API_KEY: test-key
        run: bun test src/lib --bail

      - name: Install Playwright browsers
        run: bunx playwright install --with-deps chromium

      - name: Run E2E tests
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/atspro_test
          PUBLIC_BETTER_AUTH_URL: http://localhost:5173
          ANTHROPIC_API_KEY: test-key
        run: bun run test:e2e -- --project=chromium

      # Coverage reports disabled until vitest is fixed
      # - name: Upload coverage reports
      #   uses: codecov/codecov-action@v4
      #   with:
      #     file: ./coverage/lcov.info
      #     flags: unittests
      #     name: codecov-umbrella
      #     token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results/
            playwright-report/
          retention-days: 30

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Configure npm registry
        run: |
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc || true

      - name: Clear Bun cache
        run: |
          bun pm cache rm
          rm -rf ~/.bun/install/cache

      - name: Install dependencies
        run: |
          bun install --no-cache || bun install --no-cache

      - name: Setup environment
        run: |
          cp .env.example .env

      - name: Run linter
        run: bun run lint

      - name: Check TypeScript
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/atspro_test
          PUBLIC_BETTER_AUTH_URL: http://localhost:5173
          ANTHROPIC_API_KEY: test-key
        run: bun run check
